### ISSUE TITLE
ALX Checker can't see our dev branch

### ISSUE THREAD

**Issue by Davenchy** [Davenchy/alx-files_manager#10]
The checker have been released and only the first test case passes out of 9.
The problem is related to requirements, any ideas?

**Comment by Davenchy** [comment]
Probably this is happening because the checker fetches the main branch while our development happens on the dev branch. Any ideas?
I could set the dev branch as the repo's main branch.

**Comment by M1-Elmasry** [comment]
i think so, the checker by default fetch the default branch, so we have to make dev branch our default branch until we finish

**Comment by Davenchy** [comment]
done
